---
title: "P8105 Homework 5"
author: "Diana Hernandez"
date: "2023-11-15"
output: github_document
---

Load libraries.

```{r}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal())

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

# Problem 1

Import the data.

```{r}
homicide_data =
  read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/master/homicide-data.csv")
```

The raw data has `r ncol(homicide_data)` variables and `r nrow(homicide_data)` observations. Some of the key variables include victim name, victim age, victim race, victim sex, city and state of homicide, and disposition. 

Create `city_state` variable and create summary.

```{r}
homicide_tidy =
  homicide_data |>
   mutate(
      city_state = paste0(city, ",", state)
    ) 
```

# Problem 2

Import the data.

```{r}
data_path = "./data/" 

import_csv = function(x) {
  read_csv(x) |>
  mutate(filename = x)
}

con_exp = list.files(data_path, pattern = "\\.csv$", full.names = T)

con_exp_df = map(con_exp, import_csv)

final_con_exp_data = bind_rows(con_exp_df)
```

Data wrangling.

```{r}
tidy_con_exp_data =
  final_con_exp_data |>
  mutate(
    subject_id = row_number(),
    control_arm = ifelse(subject_id < 11, "Control", "Experimental")
    ) |>
  select(subject_id, control_arm, everything(), -filename) |>
  pivot_longer(
    week_1:week_8,
    names_to = "week",
    values_to = "observations"
  )
```

Spaghetti plot.

```{r}
con_exp_plot =
tidy_con_exp_data |> 
  ggplot(aes(x = week, y = observations, group = subject_id, color = subject_id)) +
  geom_line()

con_exp_plot
```

